services:

  # ── Infrastructure ───────────────────────────────────────────

  redis:
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft Mode
      # only one broker 
      KAFKA_NODE_ID: 1
      # This is set by the broker and the cluster controller
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Listeners 
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      # Since I don't have SSL certificates signed, it won't be used
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # Cluster KRaft
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      # Topics
      # Prevents Kafka from automatically creating topics 
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  kafka-ui:
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-dev"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      SERVER_SERVLET_CONTEXT_PATH: "/kafka-ui"
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  redis-data:
    driver: local
  kafka-data:
    driver: local