services:
  redis:
    image: redis:7-alpine
    networks:
      - microservices-network

  kafka:
    image: apache/kafka:3.9.0
    networks:
      - microservices-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge